- hosts: localhost
  tasks:
   - name: epel release
     yum:
       name: epel-release
       state: latest
   
   - name: updates apt
     yum:
       name: '*'
       state: latest
   
   - name: install basic packages
     yum: name={{item}} state=latest
     with_items:
       - python-devel
       - libffi-devel
       - openssl-devel
       - python-pip
       - python-setuptools

   - name: install setuptools
     pip: name=setuptools state=latest

   - name: install tabulate
     pip: name=tabulate state=latest

   - name: install argparse
     pip: name=argparse state=latest

   - name: install networkx
     pip: name=networkx version=1.11

   - name: install six
     pip: name=six state=latest

   - name: install ryu
     pip: name=ryu state=latest
     
   - name: install oslo.config
     pip: name=oslo.config state=latest

   - name: install pytest
     pip: name=pytest state=latest

   - name: install Flask
     pip: name=Flask state=latest

   - name: install flask_restful
     pip: name=flask_restful state=latest

   - name: install requests
     pip: name=requests state=latest

   - name: install docker
     pip: name=docker version=2.0.2

   - name: install prometheus_client
     pip: name=prometheus_client state=latest

   - name: install latest urllib3 (fix error urllib3.connection.match_hostname = match_hostname)
     pip: name=urllib3 version=1.21.1

   - name: install iptc
     pip: name=python-iptables state=latest

   - name: install ipaddress
     pip: name=ipaddress state=latest

   - name: install gevent
     pip: name=gevent state=latest

   - name: install vim-emu
     shell: python setup.py develop
     args:
       chdir: ../
